<a href="https://colab.research.google.com/github/pascal-bergeron/ai4forgood2016/blob/main/DataPreparation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [35]:
import pandas as pd
import numpy as np
from google.colab import files, drive
from datetime import datetime

In [ ]:
drive.mount('/content/drive/')

In [7]:
cp 'drive/My Drive/Projects/AIForGood2020/' . -r

In [8]:
cd AIForGood2020/

/content/AIForGood2020

# 211 Dataset

In [10]:
# !unrar e -p*hack20 211GrandMontreal_DataPack.rar

UNRAR 5.50 freeware      Copyright (c) 1993-2017 Alexander Roshal


Extracting from 211GrandMontreal_DataPack.rar


Would you like to replace the existing file Références.xlsx
7966092 bytes, modified on 2020-09-04 16:05
with a new one
7966092 bytes, modified on 2020-09-04 16:05

[Y]es, [N]o, [A]ll, n[E]ver, [R]ename, [Q]uit
User break

User break

In [11]:
municipalite = pd.read_excel('Municipalités.xlsx')

In [12]:
municipalite.set_index('Municipalité_Code', inplace=True)

In [13]:
municipalite.tail(10)

                               Municipalité_Nom  ... Territoire 211 Grand Montréal
Municipalité_Code                                ...
68030                               Napierville  ...                           Oui
68035              Saint-Cyprien-de-Napierville  ...                           Oui
68040                   Saint-Jacques-le-Mineur  ...                           Oui
68045                             Saint-Édouard  ...                           Oui
68050                              Saint-Michel  ...                           Oui
68055                                Saint-Rémi  ...                           Oui
999001                            Inconnu-Laval  ...                           Oui
999004                         Inconnu-Montréal  ...                           Oui
999005                       Inconnu-Montérégie  ...                           Oui
999999                                  Inconnu  ...                       Inconnu

[10 rows x 14 columns]

In [14]:
appels = pd.read_excel('Appels.xlsx')

In [15]:
appels.set_index('CallReportNum', inplace=True)

In [16]:
print(len(appels))

101612

In [17]:
appels.tail()

              CallDateAndTimeStart  ... Municipalité_Code
CallReportNum                       ...
78144190                2020-08-31  ...           57005.0
78144749                2020-08-31  ...           66200.0
78144910                2020-08-31  ...          999999.0
78145762                2020-08-31  ...           65105.0
78146045                2020-08-31  ...           58007.0

[5 rows x 5 columns]

In [18]:
appels.groupby('StateProvince').count()

               CallDateAndTimeStart  ...  Municipalité_Code
StateProvince                        ...
AB                               16  ...                  8
BC                               10  ...                  6
MB                                3  ...                  1
NB                                1  ...                  1
NS                                4  ...                  0
ON                              119  ...                 52
QC                           101400  ...             101388
SK                                2  ...                  1
xx                               45  ...                 45

[9 rows x 4 columns]

In [19]:
appels.groupby('Municipalité_Code').count()

                   CallDateAndTimeStart  ...  Code postal court
Municipalité_Code                        ...
2015.0                                1  ...                  1
2028.0                                1  ...                  1
3005.0                                3  ...                  1
4037.0                                2  ...                  2
6013.0                                1  ...                  1
...                                 ...  ...                ...
999003.0                             96  ...                  0
999004.0                           7240  ...                  1
999005.0                            282  ...                  0
999998.0                            199  ...                  0
999999.0                            924  ...                  0

[400 rows x 4 columns]

In [20]:
calls = appels.join(municipalite,on='Municipalité_Code', how='left')

In [21]:
print('number of calls:', len(calls))
calls.tail()

number of calls: 101612

              CallDateAndTimeStart  ... Territoire 211 Grand Montréal
CallReportNum                       ...
78144190                2020-08-31  ...                        ancien
78144749                2020-08-31  ...                           Oui
78144910                2020-08-31  ...                       Inconnu
78145762                2020-08-31  ...                           Oui
78146045                2020-08-31  ...                           Oui

[5 rows x 19 columns]

In [22]:
calls.groupby('Région Administrative').count()

                                CallDateAndTimeStart  ...  Territoire 211 Grand Montréal
Région Administrative                                 ...
Abitibi-Témiscamingue                             17  ...                             17
Bas-Saint-Laurent                                 18  ...                             18
Capitale-Nationale                               182  ...                            182
Centre-du-Québec                                  45  ...                             45
Chaudière-Appalaches                              35  ...                             35
Côte-Nord                                          7  ...                              7
Estrie                                            49  ...                             49
Gaspésie--Îles-de-la-Madeleine                     9  ...                              9
Inconnu                                          924  ...                            924
Lanaudière                                      4630  ...                           4630
Laurentides                                     2700  ...                           2700
Laval                                           9478  ...                           9478
Mauricie                                          45  ...                             45
Montréal                                       74280  ...                          74280
Montérégie                                      8819  ...                           8819
Nord-du-Québec                                     9  ...                              9
Outaouais                                         52  ...                             52
Saguenay--Lac-Saint-Jean                          16  ...                             16

[18 rows x 18 columns]

In [23]:
appels_profils = pd.read_excel('Appels_Profil.xlsx')

In [24]:
appels_profils.set_index('CallReportNum', inplace=True)

In [25]:
appels_profils.tail()

                Âge Catégorie d'âge  Genre    Langue Mode De Communication
CallReportNum
78144190        2.0        0-19 ans  Femme  Français                Appels
78144749       27.0       20-29 ans  Femme  Français                Appels
78144910        NaN             NaN  Femme   Anglais                Appels
78145762       85.0  70 ans et plus  Femme  Français                Appels
78146045        4.0        0-19 ans  Homme   Anglais                Appels

In [26]:
calls2 = calls.join(appels_profils)

In [27]:
calls3  = appels.join(appels_profils)

In [29]:
calls_consolid = calls3.join(municipalite,on='Municipalité_Code', how='left')

In [31]:
.head()

              CallDateAndTimeStart  ... Territoire 211 Grand Montréal
CallReportNum                       ...
51805319                2018-04-01  ...                           Oui
51805954                2018-04-01  ...                           Oui
51806285                2018-04-01  ...                           Oui
51806377                2018-04-01  ...                           Oui
51806428                2018-04-01  ...                           Oui

[5 rows x 24 columns]

In [ ]:
# calls_consolid.to_excel('calls_consolid.xlsx')

# Number of calls per week per borrough

In [41]:
calls_consolid['week'] = calls_consolid['CallDateAndTimeStart'].dt.isocalendar().week

In [42]:
calls_consolid['year'] = calls_consolid['CallDateAndTimeStart'].dt.isocalendar().year

In [43]:
calls_consolid['year-week']  = calls_consolid.apply(lambda x : datetime.strptime(str(x['year']) + ' ' + str(x['week']) + ' 1', "%Y %W %w"), axis=1 )

In [200]:
def get_zero_count_df(df: pd.DataFrame) -> pd.DataFrame:
  min_date = df['year-week'].min().to_pydatetime()
  max_date = df['year-week'].max().to_pydatetime()
  
  date_weeks = pd.date_range(min_date, max_date, freq='7D').to_frame()
  date_weeks.columns=['year-week']
  date_weeks.set_index('year-week', inplace=True)

  munis = pd.Series(df['Municipalité_Nom'].unique())
  index = pd.MultiIndex.from_product([munis.values, date_weeks.index.values], names= ['Municipalité_Nom', 'year-week'] )
  df_out = pd.DataFrame(index = index).reset_index()
  df_out['zero_count'] = [0] * len(df_out)
  df_out.set_index(['Municipalité_Nom', 'year-week'], inplace=True)
  return df_out

In [215]:
def count_calls_per_week(df_in: pd.DataFrame) -> pd.DataFrame:
  df = df_in[['year', 'week', 'year-week', 'Municipalité_Code', 'Municipalité_Nom']].value_counts().to_frame().sort_values(by=['year-week', 'Municipalité_Nom'])
  df.columns = ['nbr_of_calls']
  df = df.reset_index()
  df = df[[ 'Municipalité_Nom','year-week', 'nbr_of_calls']]
  df.set_index(['Municipalité_Nom', 'year-week'], inplace=True)

  # print('debug')
  df_zero_count = get_zero_count_df(df_in) 
  # print(df_zero_count.groupby('Municipalité_Nom').count())
  df = df.join(df_zero_count, how='right').sort_index()
  # print(df.groupby('Municipalité_Nom').count())
  df['nbr_of_calls'] = df['nbr_of_calls'].fillna(0)
  df.drop('zero_count', axis='columns', inplace=True)
  # print(df.groupby('Municipalité_Nom').count())

  df_cumul = df.groupby(['Municipalité_Nom', 'year-week']).sum().groupby(level=[0]).transform(pd.Series.cumsum).reset_index()
  df_cumul.rename(columns={'nbr_of_calls':'cumul_nbf_of_calls'}, inplace=True)
  df_cumul.set_index(['Municipalité_Nom', 'year-week'], inplace=True)
  
  df_out = df.join(df_cumul)
  df_out = df_out.sort_index().reset_index()
  return df_out

In [218]:
mtl_calls =  calls_consolid[calls_consolid['Région Administrative'] == 'Montréal']
df_cumul = count_calls_per_week(mtl_calls)
df_cumul.head(40)

         Municipalité_Nom  year-week  nbr_of_calls  cumul_nbf_of_calls
0   Ahuntsic-Cartierville 2018-03-26           0.0                 0.0
1   Ahuntsic-Cartierville 2018-04-02          24.0                24.0
2   Ahuntsic-Cartierville 2018-04-09          34.0                58.0
3   Ahuntsic-Cartierville 2018-04-16          29.0                87.0
4   Ahuntsic-Cartierville 2018-04-23          31.0               118.0
5   Ahuntsic-Cartierville 2018-04-30          40.0               158.0
6   Ahuntsic-Cartierville 2018-05-07          37.0               195.0
7   Ahuntsic-Cartierville 2018-05-14          37.0               232.0
8   Ahuntsic-Cartierville 2018-05-21          38.0               270.0
9   Ahuntsic-Cartierville 2018-05-28          36.0               306.0
10  Ahuntsic-Cartierville 2018-06-04          36.0               342.0
11  Ahuntsic-Cartierville 2018-06-11          28.0               370.0
12  Ahuntsic-Cartierville 2018-06-18          37.0               407.0
13  Ahuntsic-Cartierville 2018-06-25          31.0               438.0
14  Ahuntsic-Cartierville 2018-07-02          33.0               471.0
15  Ahuntsic-Cartierville 2018-07-09          25.0               496.0
16  Ahuntsic-Cartierville 2018-07-16          33.0               529.0
17  Ahuntsic-Cartierville 2018-07-23          38.0               567.0
18  Ahuntsic-Cartierville 2018-07-30          20.0               587.0
19  Ahuntsic-Cartierville 2018-08-06          36.0               623.0
20  Ahuntsic-Cartierville 2018-08-13          32.0               655.0
21  Ahuntsic-Cartierville 2018-08-20          19.0               674.0
22  Ahuntsic-Cartierville 2018-08-27          35.0               709.0
23  Ahuntsic-Cartierville 2018-09-03          21.0               730.0
24  Ahuntsic-Cartierville 2018-09-10          35.0               765.0
25  Ahuntsic-Cartierville 2018-09-17          32.0               797.0
26  Ahuntsic-Cartierville 2018-09-24          35.0               832.0
27  Ahuntsic-Cartierville 2018-10-01          30.0               862.0
28  Ahuntsic-Cartierville 2018-10-08          31.0               893.0
29  Ahuntsic-Cartierville 2018-10-15          42.0               935.0
30  Ahuntsic-Cartierville 2018-10-22          46.0               981.0
31  Ahuntsic-Cartierville 2018-10-29          24.0              1005.0
32  Ahuntsic-Cartierville 2018-11-05          39.0              1044.0
33  Ahuntsic-Cartierville 2018-11-12          40.0              1084.0
34  Ahuntsic-Cartierville 2018-11-19          44.0              1128.0
35  Ahuntsic-Cartierville 2018-11-26          41.0              1169.0
36  Ahuntsic-Cartierville 2018-12-03          41.0              1210.0
37  Ahuntsic-Cartierville 2018-12-10          45.0              1255.0
38  Ahuntsic-Cartierville 2018-12-17          41.0              1296.0
39  Ahuntsic-Cartierville 2018-12-24          11.0              1307.0

In [219]:
df_cumul.to_csv('211callsByWeek_all_dates.csv')

In [221]:
# Filter to start at the same time of covid dataset
recent_mtl_calls = mtl_calls[mtl_calls['year-week'] >= datetime(2020,4,6)]
df_cumul_recent = count_calls_per_week(recent_mtl_calls)
df_cumul_recent.tail(40)

                         Municipalité_Nom  ... cumul_nbf_of_calls
765  Villeray—Saint-Michel—Parc-Extension  ...             1046.0
766  Villeray—Saint-Michel—Parc-Extension  ...             1132.0
767  Villeray—Saint-Michel—Parc-Extension  ...             1213.0
768  Villeray—Saint-Michel—Parc-Extension  ...             1274.0
769  Villeray—Saint-Michel—Parc-Extension  ...             1328.0
770  Villeray—Saint-Michel—Parc-Extension  ...             1378.0
771  Villeray—Saint-Michel—Parc-Extension  ...             1414.0
772  Villeray—Saint-Michel—Parc-Extension  ...             1460.0
773  Villeray—Saint-Michel—Parc-Extension  ...             1519.0
774  Villeray—Saint-Michel—Parc-Extension  ...             1553.0
775  Villeray—Saint-Michel—Parc-Extension  ...             1589.0
776  Villeray—Saint-Michel—Parc-Extension  ...             1627.0
777  Villeray—Saint-Michel—Parc-Extension  ...             1668.0
778  Villeray—Saint-Michel—Parc-Extension  ...             1721.0
779  Villeray—Saint-Michel—Parc-Extension  ...             1766.0
780  Villeray—Saint-Michel—Parc-Extension  ...             1808.0
781  Villeray—Saint-Michel—Parc-Extension  ...             1817.0
782                             Westmount  ...                3.0
783                             Westmount  ...                4.0
784                             Westmount  ...                6.0
785                             Westmount  ...                8.0
786                             Westmount  ...               13.0
787                             Westmount  ...               22.0
788                             Westmount  ...               26.0
789                             Westmount  ...               27.0
790                             Westmount  ...               30.0
791                             Westmount  ...               32.0
792                             Westmount  ...               34.0
793                             Westmount  ...               35.0
794                             Westmount  ...               36.0
795                             Westmount  ...               36.0
796                             Westmount  ...               39.0
797                             Westmount  ...               39.0
798                             Westmount  ...               41.0
799                             Westmount  ...               45.0
800                             Westmount  ...               49.0
801                             Westmount  ...               50.0
802                             Westmount  ...               52.0
803                             Westmount  ...               54.0
804                             Westmount  ...               54.0

[40 rows x 4 columns]

In [222]:
df_cumul.to_csv('211callsByWeek.csv')

# Organisation data consolidation

In [62]:
bdorg_general = pd.read_excel('BDorg_Général.xlsx')

In [63]:
bdorg_general.set_index('ResourceAgencyNum', inplace=True)

In [64]:
bdorg_general.tail()

                                                          PublicName  ... Custom_Acronym
ResourceAgencyNum                                                     ...
30790854                BIBLIOTHÈQUE PUBLIQUE DE DOLLARD-DES-ORMEAUX  ...            NaN
51229060                      BIBLIOTHÈQUE MUNICIPALE DE NAPIERVILLE  ...            NaN
49492168           BIBLIOTHÈQUE MUNICIPALE DE SAINT-JACQUES-LE-MI...  ...            NaN
18766848               BOISBRIAND - LOISIRS, CULTURE ET BIBLIOTHÈQUE  ...            NaN
42388216                                                 REBOND (LE)  ...            NaN

[5 rows x 10 columns]

In [65]:
bdorg_general.groupby("TaxonomyLevelName").count()

                   PublicName  ...  Custom_Acronym
TaxonomyLevelName              ...
Agency                   3303  ...            1288
Program                  2253  ...             495

[2 rows x 9 columns]

In [66]:
bdorg_localisation = pd.read_excel('BDorg_Localisation.xlsx')

In [67]:
bdorg_localisation.set_index('ResourceAgencyNum', inplace=True)

In [68]:
bdorg_localisation.tail()

                   Municipalité_Code  ...  Longitude
ResourceAgencyNum                     ...
18764121                         NaN  ... -73.823365
42810221                         NaN  ... -79.810330
33806083                     76065.0  ... -79.761240
54590531                     94250.0  ...        NaN
18762170                     81017.0  ... -78.085580

[5 rows x 7 columns]

In [69]:
bdorg_taxonomies = pd.read_excel('BDorg_Taxonomies.xlsx')

In [70]:
bdorg_taxonomies.set_index('ResourceAgencyNum', inplace=True)

In [72]:
bdorg_taxonomies = bdorg_taxonomies['TaxonomyCodes']

In [73]:
bdorg_taxonomies.tail()

ResourceAgencyNum
40054459    HH-0500.0500; PL-7400.1500 * YG-2000; HH-4500....
40450084                           PS-8000.1900; YH-0300.6150
41667289             BD-1800.2000; BD-1875.2700; TI-1800.2000
50426073    BD-2600.1500; BD-5000.1470; BD-1800.6400; BM-6...
54223611             BD-5000.4500; TI-1800.2000; BD-1875.2700
Name: TaxonomyCodes, dtype: object

In [74]:
bdorg_territoire = pd.read_excel('BDorg_Territoire desservi.xlsx')

In [75]:
bdorg_territoire.set_index('ResourceAgencyNum', inplace=True)

In [76]:
bdorg_territoire.tail()

                                                            Coverage
ResourceAgencyNum
40622563                       QC - Montérégie County - Châteauguay;
25558723                         QC - Montréal County - Ville-Marie;
40054459           QC - Montréal County - Baie-D'Urfé; QC - Montr...
41667289                             QC - Montréal County - LaSalle;
50426073           QC - Montréal County - Baie-D'Urfé; QC - Montr...

In [77]:
bdorg_information = pd.read_excel('BDorg_information.xlsx')

In [78]:
bdorg_information.tail()

      ResourceAgencyNum  ...                           Custom_Disability Access
5551           18765363  ...  Accessible aux fauteuils roulants; Stationneme...
5552           39285086  ...  Accessible aux fauteuils roulants; Stationneme...
5553           18765093  ...                  Accessible aux fauteuils roulants
5554           18762620  ...                                                NaN
5555           41667289  ...  Accessible aux fauteuils roulants; Stationneme...

[5 rows x 12 columns]

In [93]:
organisation = bdorg_general.join(bdorg_localisation).join(bdorg_territoire).join(bdorg_taxonomies)

In [94]:
organisation.head()

                                                     PublicName  ...                                      TaxonomyCodes
ResourceAgencyNum                                                ...
34515394           ACTION CONCERTATION VIEILLISSEMENT LONGUEUIL  ...                TD-6500 * YZ-6100; TD-1600.3100-800
18764735                      CENTRE COMMUNAUTAIRE PETIT ESPOIR  ...  TC-5500.6000; YH-6000.3100; ND-3500; HH-0500.8...
18762709                                       BARREAU DE LAVAL  ...                                   TN-4600; FT-4800
18765353                  COMPTOIR D'ENTRAIDE POPULAIRE MIRABEL  ...  BM-8500; BD-1800.2000; TI-1800.1500; TI-1800.6...
54247598                         LES JONATHAN DE SOULANGES INC.  ...  TD-1600.3100-180 * YF-1800.5000; PS-8000.3000 ...

[5 rows x 19 columns]

In [109]:
organisation.to_excel('organisation.xlsx')

# Needs

In [79]:
besoins = pd.read_excel('Besoins.xlsx')

In [80]:
besoins.set_index('ReportNeedNum', inplace=True)

In [81]:
besoins.tail()

               CallReportNum  ... TaxonomyName_link
ReportNeedNum                 ...
21475026            78145762  ...               NaN
21475411            78146045  ...               NaN
21475365            78146045  ...               NaN
21475383            78146045  ...               NaN
21475338            78146045  ...               NaN

[5 rows x 20 columns]

In [82]:
besoins.groupby('NeedWasUnmet').count()

              CallReportNum  ...  TaxonomyName_link
NeedWasUnmet                 ...
False                139316  ...              27676
True                   3400  ...                442

[2 rows x 19 columns]

# References

In [97]:
references = pd.read_excel('Références.xlsx')

In [98]:
references= references[['CallReportNum','ReportNeedNum', 'ResourceAgencyNum','AgencyNamePublic']]

In [99]:
# references.set_index(['CallReportNum','ReportNeedNum', 'ResourceAgencyNum'], inplace=True, )

In [100]:
references.head()

   CallReportNum  ...                                   AgencyNamePublic
0       51805319  ...                             SOS VIOLENCE CONJUGALE
1       51805954  ...                        MISSIONNAIRES DE LA CHARITÉ
2       51805954  ...                                 DÎNERS SAINT-LOUIS
3       51806285  ...                             CENTRE DE CRISE TRACOM
4       51806377  ...  CENTRE HUMANITAIRE D'ORGANISATION, DE RESSOURC...

[5 rows x 4 columns]

In [107]:
print('number of agencies that have been recommended:', len(references['ResourceAgencyNum'].unique()))

number of agencies that have been recommended: 4732