<a href="https://colab.research.google.com/github/pascal-bergeron/ai4forgood2016/blob/main/DataPreparation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [35]:
import pandas as pd
import numpy as np
from google.colab import files, drive
from datetime import datetime

In [ ]:
drive.mount('/content/drive/')

In [7]:
cp 'drive/My Drive/Projects/AIForGood2020/' . -r

In [8]:
cd AIForGood2020/

/content/AIForGood2020

# 211 Dataset

In [10]:
# !unrar e -p*hack20 211GrandMontreal_DataPack.rar

UNRAR 5.50 freeware      Copyright (c) 1993-2017 Alexander Roshal


Extracting from 211GrandMontreal_DataPack.rar


Would you like to replace the existing file Références.xlsx
7966092 bytes, modified on 2020-09-04 16:05
with a new one
7966092 bytes, modified on 2020-09-04 16:05

[Y]es, [N]o, [A]ll, n[E]ver, [R]ename, [Q]uit
User break

User break

In [11]:
municipalite = pd.read_excel('Municipalités.xlsx')

In [12]:
municipalite.set_index('Municipalité_Code', inplace=True)

In [13]:
municipalite.tail(10)

                               Municipalité_Nom  ... Territoire 211 Grand Montréal
Municipalité_Code                                ...
68030                               Napierville  ...                           Oui
68035              Saint-Cyprien-de-Napierville  ...                           Oui
68040                   Saint-Jacques-le-Mineur  ...                           Oui
68045                             Saint-Édouard  ...                           Oui
68050                              Saint-Michel  ...                           Oui
68055                                Saint-Rémi  ...                           Oui
999001                            Inconnu-Laval  ...                           Oui
999004                         Inconnu-Montréal  ...                           Oui
999005                       Inconnu-Montérégie  ...                           Oui
999999                                  Inconnu  ...                       Inconnu

[10 rows x 14 columns]

In [14]:
appels = pd.read_excel('Appels.xlsx')

In [15]:
appels.set_index('CallReportNum', inplace=True)

In [16]:
print(len(appels))

101612

In [17]:
appels.tail()

              CallDateAndTimeStart  ... Municipalité_Code
CallReportNum                       ...
78144190                2020-08-31  ...           57005.0
78144749                2020-08-31  ...           66200.0
78144910                2020-08-31  ...          999999.0
78145762                2020-08-31  ...           65105.0
78146045                2020-08-31  ...           58007.0

[5 rows x 5 columns]

In [18]:
appels.groupby('StateProvince').count()

               CallDateAndTimeStart  ...  Municipalité_Code
StateProvince                        ...
AB                               16  ...                  8
BC                               10  ...                  6
MB                                3  ...                  1
NB                                1  ...                  1
NS                                4  ...                  0
ON                              119  ...                 52
QC                           101400  ...             101388
SK                                2  ...                  1
xx                               45  ...                 45

[9 rows x 4 columns]

In [19]:
appels.groupby('Municipalité_Code').count()

                   CallDateAndTimeStart  ...  Code postal court
Municipalité_Code                        ...
2015.0                                1  ...                  1
2028.0                                1  ...                  1
3005.0                                3  ...                  1
4037.0                                2  ...                  2
6013.0                                1  ...                  1
...                                 ...  ...                ...
999003.0                             96  ...                  0
999004.0                           7240  ...                  1
999005.0                            282  ...                  0
999998.0                            199  ...                  0
999999.0                            924  ...                  0

[400 rows x 4 columns]

In [20]:
calls = appels.join(municipalite,on='Municipalité_Code', how='left')

In [21]:
print('number of calls:', len(calls))
calls.tail()

number of calls: 101612

              CallDateAndTimeStart  ... Territoire 211 Grand Montréal
CallReportNum                       ...
78144190                2020-08-31  ...                        ancien
78144749                2020-08-31  ...                           Oui
78144910                2020-08-31  ...                       Inconnu
78145762                2020-08-31  ...                           Oui
78146045                2020-08-31  ...                           Oui

[5 rows x 19 columns]

In [22]:
calls.groupby('Région Administrative').count()

                                CallDateAndTimeStart  ...  Territoire 211 Grand Montréal
Région Administrative                                 ...
Abitibi-Témiscamingue                             17  ...                             17
Bas-Saint-Laurent                                 18  ...                             18
Capitale-Nationale                               182  ...                            182
Centre-du-Québec                                  45  ...                             45
Chaudière-Appalaches                              35  ...                             35
Côte-Nord                                          7  ...                              7
Estrie                                            49  ...                             49
Gaspésie--Îles-de-la-Madeleine                     9  ...                              9
Inconnu                                          924  ...                            924
Lanaudière                                      4630  ...                           4630
Laurentides                                     2700  ...                           2700
Laval                                           9478  ...                           9478
Mauricie                                          45  ...                             45
Montréal                                       74280  ...                          74280
Montérégie                                      8819  ...                           8819
Nord-du-Québec                                     9  ...                              9
Outaouais                                         52  ...                             52
Saguenay--Lac-Saint-Jean                          16  ...                             16

[18 rows x 18 columns]

In [23]:
appels_profils = pd.read_excel('Appels_Profil.xlsx')

In [24]:
appels_profils.set_index('CallReportNum', inplace=True)

In [25]:
appels_profils.tail()

                Âge Catégorie d'âge  Genre    Langue Mode De Communication
CallReportNum
78144190        2.0        0-19 ans  Femme  Français                Appels
78144749       27.0       20-29 ans  Femme  Français                Appels
78144910        NaN             NaN  Femme   Anglais                Appels
78145762       85.0  70 ans et plus  Femme  Français                Appels
78146045        4.0        0-19 ans  Homme   Anglais                Appels

In [26]:
calls2 = calls.join(appels_profils)

In [27]:
calls3  = appels.join(appels_profils)

In [29]:
calls_consolid = calls3.join(municipalite,on='Municipalité_Code', how='left')

In [31]:
.head()

              CallDateAndTimeStart  ... Territoire 211 Grand Montréal
CallReportNum                       ...
51805319                2018-04-01  ...                           Oui
51805954                2018-04-01  ...                           Oui
51806285                2018-04-01  ...                           Oui
51806377                2018-04-01  ...                           Oui
51806428                2018-04-01  ...                           Oui

[5 rows x 24 columns]

In [ ]:
# calls_consolid.to_excel('calls_consolid.xlsx')

# Number of calls per week per borrough

In [41]:
calls_consolid['week'] = calls_consolid['CallDateAndTimeStart'].dt.isocalendar().week

In [42]:
calls_consolid['year'] = calls_consolid['CallDateAndTimeStart'].dt.isocalendar().year

In [43]:
calls_consolid['year-week']  = calls_consolid.apply(lambda x : datetime.strptime(str(x['year']) + ' ' + str(x['week']) + ' 1', "%Y %W %w"), axis=1 )

In [59]:
def count_calls_per_week(df_in: pd.DataFrame) -> pd.DataFrame:
  df = df_in[['year', 'week', 'year-week', 'Municipalité_Code', 'Municipalité_Nom']].value_counts().to_frame().sort_values(by=['year-week', 'Municipalité_Nom'])
  df.columns = ['nbr_of_calls']
  df = df.reset_index()
  df = df[[ 'Municipalité_Nom','year-week', 'nbr_of_calls']]
  df.set_index(['Municipalité_Nom', 'year-week'], inplace=True)
  df_cumul = df.groupby(['Municipalité_Nom', 'year-week']).sum().groupby(level=[0]).transform(pd.Series.cumsum).reset_index()
  df_cumul.rename(columns={'nbr_of_calls':'cumul_nbf_of_calls'}, inplace=True)
  df_cumul.set_index(['Municipalité_Nom', 'year-week'], inplace=True)
  df_out = df.join(df_cumul)
  df_out = df_out.sort_index().reset_index()
  return df_out

In [60]:
mtl_calls =  calls_consolid[calls_consolid['Région Administrative'] == 'Montréal']
df_cumul = count_calls_per_week(mtl_calls)
df_cumul.head(40)

         Municipalité_Nom  year-week  nbr_of_calls  cumul_nbf_of_calls
0   Ahuntsic-Cartierville 2018-04-02            24                  24
1   Ahuntsic-Cartierville 2018-04-09            34                  58
2   Ahuntsic-Cartierville 2018-04-16            29                  87
3   Ahuntsic-Cartierville 2018-04-23            31                 118
4   Ahuntsic-Cartierville 2018-04-30            40                 158
5   Ahuntsic-Cartierville 2018-05-07            37                 195
6   Ahuntsic-Cartierville 2018-05-14            37                 232
7   Ahuntsic-Cartierville 2018-05-21            38                 270
8   Ahuntsic-Cartierville 2018-05-28            36                 306
9   Ahuntsic-Cartierville 2018-06-04            36                 342
10  Ahuntsic-Cartierville 2018-06-11            28                 370
11  Ahuntsic-Cartierville 2018-06-18            37                 407
12  Ahuntsic-Cartierville 2018-06-25            31                 438
13  Ahuntsic-Cartierville 2018-07-02            33                 471
14  Ahuntsic-Cartierville 2018-07-09            25                 496
15  Ahuntsic-Cartierville 2018-07-16            33                 529
16  Ahuntsic-Cartierville 2018-07-23            38                 567
17  Ahuntsic-Cartierville 2018-07-30            20                 587
18  Ahuntsic-Cartierville 2018-08-06            36                 623
19  Ahuntsic-Cartierville 2018-08-13            32                 655
20  Ahuntsic-Cartierville 2018-08-20            19                 674
21  Ahuntsic-Cartierville 2018-08-27            35                 709
22  Ahuntsic-Cartierville 2018-09-03            21                 730
23  Ahuntsic-Cartierville 2018-09-10            35                 765
24  Ahuntsic-Cartierville 2018-09-17            32                 797
25  Ahuntsic-Cartierville 2018-09-24            35                 832
26  Ahuntsic-Cartierville 2018-10-01            30                 862
27  Ahuntsic-Cartierville 2018-10-08            31                 893
28  Ahuntsic-Cartierville 2018-10-15            42                 935
29  Ahuntsic-Cartierville 2018-10-22            46                 981
30  Ahuntsic-Cartierville 2018-10-29            24                1005
31  Ahuntsic-Cartierville 2018-11-05            39                1044
32  Ahuntsic-Cartierville 2018-11-12            40                1084
33  Ahuntsic-Cartierville 2018-11-19            44                1128
34  Ahuntsic-Cartierville 2018-11-26            41                1169
35  Ahuntsic-Cartierville 2018-12-03            41                1210
36  Ahuntsic-Cartierville 2018-12-10            45                1255
37  Ahuntsic-Cartierville 2018-12-17            41                1296
38  Ahuntsic-Cartierville 2018-12-24            11                1307
39  Ahuntsic-Cartierville 2019-01-07            18                1325

In [ ]:
# df_cumul.to_csv('211callsByWeek_all_dates.csv')

In [61]:
# Filter to start at the same time of covid dataset
recent_mtl_calls = mtl_calls[mtl_calls['year-week'] >= datetime(2020,4,6)]
df_cumul_recent = count_calls_per_week(recent_mtl_calls)
df_cumul_recent.head(40)

         Municipalité_Nom  year-week  nbr_of_calls  cumul_nbf_of_calls
0   Ahuntsic-Cartierville 2020-04-06            87                  87
1   Ahuntsic-Cartierville 2020-04-13           175                 262
2   Ahuntsic-Cartierville 2020-04-20           135                 397
3   Ahuntsic-Cartierville 2020-04-27           114                 511
4   Ahuntsic-Cartierville 2020-05-04            89                 600
5   Ahuntsic-Cartierville 2020-05-11            92                 692
6   Ahuntsic-Cartierville 2020-05-18            88                 780
7   Ahuntsic-Cartierville 2020-05-25            58                 838
8   Ahuntsic-Cartierville 2020-06-01            67                 905
9   Ahuntsic-Cartierville 2020-06-08            48                 953
10  Ahuntsic-Cartierville 2020-06-15            60                1013
11  Ahuntsic-Cartierville 2020-06-22            41                1054
12  Ahuntsic-Cartierville 2020-06-29            45                1099
13  Ahuntsic-Cartierville 2020-07-06            33                1132
14  Ahuntsic-Cartierville 2020-07-13            42                1174
15  Ahuntsic-Cartierville 2020-07-20            28                1202
16  Ahuntsic-Cartierville 2020-07-27            45                1247
17  Ahuntsic-Cartierville 2020-08-03            39                1286
18  Ahuntsic-Cartierville 2020-08-10            29                1315
19  Ahuntsic-Cartierville 2020-08-17            44                1359
20  Ahuntsic-Cartierville 2020-08-24            49                1408
21  Ahuntsic-Cartierville 2020-08-31            47                1455
22  Ahuntsic-Cartierville 2020-09-07            15                1470
23                  Anjou 2020-04-06            28                  28
24                  Anjou 2020-04-13            26                  54
25                  Anjou 2020-04-20            37                  91
26                  Anjou 2020-04-27            56                 147
27                  Anjou 2020-05-04            39                 186
28                  Anjou 2020-05-11            42                 228
29                  Anjou 2020-05-18            33                 261
30                  Anjou 2020-05-25            21                 282
31                  Anjou 2020-06-01            18                 300
32                  Anjou 2020-06-08            18                 318
33                  Anjou 2020-06-15            18                 336
34                  Anjou 2020-06-22            11                 347
35                  Anjou 2020-06-29            18                 365
36                  Anjou 2020-07-06            13                 378
37                  Anjou 2020-07-13            10                 388
38                  Anjou 2020-07-20            17                 405
39                  Anjou 2020-07-27            15                 420

In [ ]:
# df_cumul_recent.to_csv('211callsByWeek.csv')

# Data preparation for recommender

In [ ]:
bdorg_contacts = pd.read_excel('BDorg_Contact.xlsx')

In [ ]:
bdorg_contacts.set_index('ResourceAgencyNum', inplace=True)

In [ ]:
bdorg_contacts.tail()

                     Phone1Number  ...             Custom_Twitter
ResourceAgencyNum                  ...
18760880             514 842-4464  ...   twitter.com/shrinershosp
18760573           1 800 363-6048  ...           twitter.com/oiiq
18765867           1 877 356-3226  ...  twitter.com/croixrouge_qc
18760090             514 526-1699  ...     twitter.com/Pasdelarue
18763900                      NaN  ...       twitter.com/educaloi

[5 rows x 10 columns]

In [ ]:
bdorg_general = pd.read_excel('BDorg_Général.xlsx')

In [ ]:
bdorg_general.set_index('ResourceAgencyNum', inplace=True)

In [ ]:
bdorg_general.tail()

                                                          PublicName  ... Custom_Acronym
ResourceAgencyNum                                                     ...
30790854                BIBLIOTHÈQUE PUBLIQUE DE DOLLARD-DES-ORMEAUX  ...            NaN
51229060                      BIBLIOTHÈQUE MUNICIPALE DE NAPIERVILLE  ...            NaN
49492168           BIBLIOTHÈQUE MUNICIPALE DE SAINT-JACQUES-LE-MI...  ...            NaN
18766848               BOISBRIAND - LOISIRS, CULTURE ET BIBLIOTHÈQUE  ...            NaN
42388216                                                 REBOND (LE)  ...            NaN

[5 rows x 10 columns]

In [ ]:
bdorg_general.groupby("TaxonomyLevelName").count()

                   PublicName  ...  Custom_Acronym
TaxonomyLevelName              ...
Agency                   3303  ...            1288
Program                  2253  ...             495

[2 rows x 9 columns]

In [ ]:
bdorg_localisation = pd.read_excel('BDorg_Localisation.xlsx')

In [ ]:
bdorg_localisation.set_index('ResourceAgencyNum', inplace=True)

In [ ]:
bdorg_localisation.tail()

                   Municipalité_Code  ...  Longitude
ResourceAgencyNum                     ...
18764121                         NaN  ... -73.823365
42810221                         NaN  ... -79.810330
33806083                     76065.0  ... -79.761240
54590531                     94250.0  ...        NaN
18762170                     81017.0  ... -78.085580

[5 rows x 7 columns]

In [ ]:
bdorg_taxonomies = pd.read_excel('BDorg_Taxonomies.xlsx')

In [ ]:
bdorg_taxonomies.set_index('ResourceAgencyNum', inplace=True)

In [ ]:
bdorg_taxonomies.tail()

                                                       TaxonomyCodes                                       TaxonomyTerm
ResourceAgencyNum
40054459           HH-0500.0500; PL-7400.1500 * YG-2000; HH-4500....  Éducation de base des adultes; Cours d'informa...
40450084                                  PS-8000.1900; YH-0300.6150  Clubs sociaux ethnoculturels; Communauté nigér...
41667289                    BD-1800.2000; BD-1875.2700; TI-1800.2000  Banques alimentaires; Récupération d'aliments ...
50426073           BD-2600.1500; BD-5000.1470; BD-1800.6400; BM-6...  Jardins communautaires; Repas communautaires; ...
54223611                    BD-5000.4500; TI-1800.2000; BD-1875.2700  Repas à faible coût; Dons de nourriture; Récup...

In [ ]:
bdorg_territoire = pd.read_excel('BDorg_Territoire desservi.xlsx')

In [ ]:
bdorg_territoire.set_index('ResourceAgencyNum', inplace=True)

In [ ]:
bdorg_territoire.tail()

                                                            Coverage
ResourceAgencyNum
40622563                       QC - Montérégie County - Châteauguay;
25558723                         QC - Montréal County - Ville-Marie;
40054459           QC - Montréal County - Baie-D'Urfé; QC - Montr...
41667289                             QC - Montréal County - LaSalle;
50426073           QC - Montréal County - Baie-D'Urfé; QC - Montr...

In [ ]:
bdorg_information = pd.read_excel('BDorg_information.xlsx')

In [ ]:
bdorg_information.tail()

      ResourceAgencyNum  ...                           Custom_Disability Access
5551           18765363  ...  Accessible aux fauteuils roulants; Stationneme...
5552           39285086  ...  Accessible aux fauteuils roulants; Stationneme...
5553           18765093  ...                  Accessible aux fauteuils roulants
5554           18762620  ...                                                NaN
5555           41667289  ...  Accessible aux fauteuils roulants; Stationneme...

[5 rows x 12 columns]

In [6]:
besoins = pd.read_excel('Besoins.xlsx')

FileNotFoundError: ignored

In [1]:
besoins.set_index('ReportNeedNum', inplace=True)

NameError: ignored

In [158]:
besoins.tail()

                                                               TaxonomyName_full  ...  TaxonomyName_link
CallReportNum TaxonomyCode_full                                                   ...
78145762      TI-1800.4500-100                    Dons de livres et de magazines  ...                NaN
78146045      NL-3000.1500                Aide pour les frais de garde d'enfants  ...                NaN
              PH-6100.1500                    Cours de développement de l'enfant  ...                NaN
              PH-6100.3300                        Éducation parentale à domicile  ...                NaN
              PH-2360.1800       Centres de services à l'enfance et aux familles  ...                NaN

[5 rows x 19 columns]

In [159]:
besoins.groupby('NeedWasUnmet').count()

              TaxonomyName_full  ...  TaxonomyName_link
NeedWasUnmet                     ...
False                    139316  ...              27676
True                       3400  ...                442

[2 rows x 18 columns]

In [162]:
besoins[besoins['NeedWasUnmet'] == True]

                                                               TaxonomyName_full  ...  TaxonomyName_link
CallReportNum TaxonomyCode_full                                                   ...
51853289      BH-5000.5000                                           Déménageurs  ...                NaN
51854786      BT-4500.6500-500               Transport pour rendez-vous médicaux  ...                NaN
51860944      HH-0500.8000-150                            Anglais langue seconde  ...                NaN
51887256      PH-7000.6000 * YB-9500.1500     Soins de relève externes * Enfants  ...            Enfants
51893944      PH-3300.3100                         Services d'employés de maison  ...                NaN
...                                                                          ...  ...                ...
78120622      TE-8920.6600-160             Recyclage des déchets de construction  ...                NaN
78125714      TI-1800.3000-200                        Dons de mobilier de maison  ...                NaN
78132706      PH-3300.3100                                     Entretien ménager  ...                NaN
78134486      BH-3800                            Aide pour les frais de logement  ...                NaN
78138680      TI-1800.8500                         Dons d'outils et d'équipement  ...                NaN

[3400 rows x 19 columns]

In [176]:
references = pd.read_excel('Références.xlsx')

In [167]:
references.set_index(['CallReportNum',	'ResourceAgencyNum'], inplace=True, )

In [169]:
references.head()

                                                                  AgencyNamePublic  ReportNeedNum
CallReportNum ResourceAgencyNum
51805319      18762230.0                                    SOS VIOLENCE CONJUGALE       12443066
51805954      18760351.0                               MISSIONNAIRES DE LA CHARITÉ       12443170
              18762550.0                                        DÎNERS SAINT-LOUIS       12443170
51806285      18762497.0                                    CENTRE DE CRISE TRACOM       12443222
51806377      18763063.0         CENTRE HUMANITAIRE D'ORGANISATION, DE RESSOURC...       12443241

In [173]:
len(references['ResourceAgencyNum'].count())

4732

In [182]:
resource_ref_count= references.groupby('ResourceAgencyNum')['CallReportNum'].count().sort_values(ascending=False)

In [194]:
resource_agency_nums = resource_ref_count[resource_ref_count > 10].index.astype(int).values
np.sort(resource_agency_nums)

array([18759962, 18759964, 18759965, ..., 68848329, 68933670, 69147049])

array([18759962, 18759964, 18759965, ..., 68848329, 68933670, 69147049])

**311 Dataset**

In [ ]:
!unzip requetes311.zip

Archive:  requetes311.zip
  inflating: requetes311.csv

In [ ]:
requetes311 = pd.read_csv('requetes311.csv')

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (0,3,4,5,6,8,9,10,27) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [ ]:
requetes311.tail()

           ID_UNIQUE   NATURE  ...   DERNIER_STATUT  DATE_DERNIER_STATUT
3803042  13-317913-B  Requete  ...         Terminée  2017-11-07T08:04:37
3803043  13-313550-D  Requete  ...  Prise en charge  2020-07-22T06:51:11
3803044  13-313550-C  Requete  ...         Terminée  2018-05-03T08:06:30
3803045  13-313550-B  Requete  ...         Terminée  2018-01-17T10:37:13
3803046  10-182618-A  Requete  ...         Terminée  2018-11-01T06:51:40

[5 rows x 29 columns]

In [ ]:
requetes311_2014_2015 = pd.read_csv('requetes311_2014_2015.csv')

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (0,3,4,5,6,8,9,10) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [ ]:
requetes311_2014_2015.tail()

        ID_UNIQUE   NATURE  ...          LOC_X         LOC_Y
1577194      14-5  Requete  ...  303360.884114  5.051549e+06
1577195      14-4  Requete  ...  303346.810000  5.051506e+06
1577196      14-3  Requete  ...  299245.181000  5.037722e+06
1577197      14-2  Requete  ...  300340.653000  5.044892e+06
1577198      14-1  Requete  ...  299034.643141  5.046517e+06

[5 rows x 27 columns]

Institut de la statistique du Québec
https://www.stat.gouv.qc.ca/statistiques/profils/profil06/06ra_index.htm#conditions_vie

In [ ]:
menages06 = pd.read_excel('menages06.xlsx')

In [ ]:
menages06.head()

  Répartition de la clientèle prestataire des programmes d'aide financière de dernier recours selon le programme, Montréal et ensemble du Québec, 2014-2018¹  ... Unnamed: 12
0                                                NaN                                                                                                          ...         NaN
1                                                NaN                                                                                                          ...      2018.0
2                                           Montréal                                                                                                          ...         NaN
3                             Nombre de prestataires                                                                                                          ...     35713.0
4                                            Adultes                                                                                                          ...     32851.0

[5 rows x 13 columns]

**COVID 19 par Arrondissements-montreal**

In [ ]:
data_covid19_montreal = pd.read_csv('covid19-par-arrondissements-montreal/data/2020-03-29.csv')

In [ ]:
data_covid19_montreal.head()

                         Arrondissements  Cas Confirmés
0                  Ahuntsic–Cartierville             54
1                                  Anjou              9
2                           Baie-D'Urfé              2
3                           Beaconsfield             10
4  Côte-des-Neiges–Notre-Dame-de-Grâce            161

Courbe Covid
https://santemontreal.qc.ca/en/public/coronavirus-covid-19/situation-of-the-coronavirus-covid-19-in-montreal/#c43710

In [ ]:
courbe_Covid = pd.read_csv('courbe_Covid.csv', sep=';')

In [ ]:
courbe_Covid.head()

         Date  Nouveaux cas  Cumulatif de cas  Unnamed: 3
0  2020-01-08           0.0               0.0         NaN
1  2020-02-25           1.0               1.0         NaN
2  2020-02-26           0.0               1.0         NaN
3  2020-02-27           0.0               1.0         NaN
4  2020-02-28           0.0               1.0         NaN

In [ ]:
covid19_download = pd.read_csv('covid19-download.csv')

In [ ]:
covid19_download.tail()

      pruid                  prname  ... avgdeaths_last7 avgratedeaths_last7
3757     60                   Yukon  ...             0.0                0.00
3758     61   Northwest Territories  ...             0.0                0.00
3759     62                 Nunavut  ...             0.0                0.00
3760     99  Repatriated travellers  ...             0.0                 NaN
3761      1                  Canada  ...            55.0                0.15

[5 rows x 35 columns]

Centraide Radar

In [ ]:
radar_uwc_data = pd.read_excel('Copie de Radar_UWC_DATA_16102020.xlsx')

In [ ]:
radar_uwc_data.head()

     #ID211 #ID Centraide  ... Autres soutiens Montant 5        UWC_Market
0  18761998     A-7800539  ...                       NaN               NaN
1       NaN     A-7800583  ...                       NaN               NaN
2  23241186     A-7807772  ...                       NaN               NaN
3  55456858           NaN  ...                       NaN  Greater Montreal
4  18760692     A-7800017  ...                       NaN  Greater Montreal

[5 rows x 43 columns]

In [ ]:
radar_uwc_investissements_reguliers = pd.read_excel('RADAR_UWC_INVESTISSEMENTSREGULIERS.xlsx')

In [ ]:
radar_uwc_investissements_reguliers.head()

     #ID211 #ID Centraide  ... Autres soutiens Montant 5        UWC_Market
0  18761998     A-7800539  ...                       NaN               NaN
1       NaN     A-7800583  ...                       NaN               NaN
2  23241186     A-7807772  ...                       NaN               NaN
3  18760692     A-7800017  ...                       NaN  Greater Montreal
4  18761973     A-7801484  ...                       NaN  Greater Montreal

[5 rows x 43 columns]

Weather

In [ ]:
weather = pd.read_csv('en_climate_daily_QC_702S006_2020_P1D.csv')

In [ ]:
weather.head()

   Longitude (x)  Latitude (y)  ... Spd of Max Gust (km/h) Spd of Max Gust Flag
0         -73.74         45.47  ...                   36.0                  NaN
1         -73.74         45.47  ...                   32.0                  NaN
2         -73.74         45.47  ...                    NaN                  NaN
3         -73.74         45.47  ...                    NaN                  NaN
4         -73.74         45.47  ...                   42.0                  NaN

[5 rows x 31 columns]

Données ouvertes ville de Montréal

In [ ]:
actes_criminels = pd.read_csv('interventionscitoyendo.csv', encoding = "ISO-8859-1")

In [ ]:
actes_criminels.tail()

                       CATEGORIE        DATE  ...  LONGITUDE   LATITUDE
179408                    Méfait  2020-05-31  ... -73.562202  45.511716
179409                    Méfait  2020-05-31  ... -73.562202  45.511716
179410  Vol de véhicule à moteur  2020-03-04  ... -73.562202  45.511716
179411  Vol de véhicule à moteur  2020-08-02  ... -73.676647  45.521969
179412  Vol de véhicule à moteur  2020-09-30  ... -73.626307  45.566936

[5 rows x 8 columns]